### ISSUE TITLE
Dependabot alert: node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor

### ISSUE THREAD

**Issue by thomasmerz** [inokawa/lang-box#11]
Details can be found [here](https://github.com/thomasmerz/lang-box/security/dependabot/1) ⚠️ 
Proposed action:
> Upgrade node-fetch to version 2.6.7 or later. For example:

**Comment by thomasmerz** [comment]
I  disabled Actions until this issue will be fixed.

**Comment by inokawa** [comment]
Thank you for reporting.
