### ISSUE TITLE
How can I keep my repo (created from template) current with this repo?

### ISSUE THREAD

**Issue by thomasmerz** [inokawa/lang-box#21]
I keep all my (forked) repos current with upstream-repos by using an `upstream` branch in my (forked) repos:

```
# create:
git remote add upstream "$1"
git checkout -b upstream
git push --set-upstream origin upstream

# update by rebasing from upstream-branch:
if git checkout upstream; then
  if git pull upstream HEAD; then
    git push || exit 1
  fi
else
  exit 1
fi
git checkout "$(git remote show origin|grep "HEAD branch"|cut -d":" -f2|tr -d " ")" && git pull
if git rebase upstream; then
  git push || exit 1
else
  exit 1
fi
```

This works great for **forked** repos, but repo can only be used as a template in a **new** repo, so any update in this repo can't be sync'ed into repos that other users use.

Do you have any idea how to fix or circumvent this? 🤔

**Comment by thomasmerz** [comment]
As you can see https://github.com/thomasmerz/lang-box has been generated, not forked:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/18568381/207588958-8d2fe357-d396-40a1-a0e8-a4ecd2262c82.png">

And yours can only be used as a template for **new** repos:
<img width="879" alt="image" src="https://user-images.githubusercontent.com/18568381/207589177-180391f1-d04c-4947-8d21-a08434233117.png">

**Comment by inokawa** [comment]
I'm not confident but I think GitHub's template is a boilerplate for new repo.
So you should choose fork in that case.

**Comment by thomasmerz** [comment]
You're absolutely right - I focussed only on this green-heavy-"User this template"-button. Sorry, for the confusion… 🥳
