### ISSUE TITLE
TypeError: Cannot read property 'paths' of undefined

### ISSUE THREAD

**Issue by mskangg** [inokawa/lang-box#4]
hi, inokawa!
First of all, I would like to thank you for providing a good box.

Howerver, There is an error in Run npm start and it does not work.
Is it my own problem?
Please check my error message.

```
TypeError: Cannot read property 'paths' of undefined
    at file:///home/runner/work/lang-box/lang-box/src/linguist.js:36:22
    at Array.forEach (<anonymous>)
    at parseOutput (file:///home/runner/work/lang-box/lang-box/src/linguist.js:21:20)
    at runLinguist (file:///home/runner/work/lang-box/lang-box/src/linguist.js:83:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async file:///home/runner/work/lang-box/lang-box/src/index.js:103:19
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lang-box@1.0.0 start: `node --experimental-modules --es-module-specifier-resolution=node src/index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lang-box@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-03-27T09_02_37_963Z-debug.log
Error: Process completed with exit code 1.
```

**Comment by inokawa** [comment]
Hi, 
I couldn't judge what causes the error but I add guard to suppress the error.
Could you try it again please?

**Comment by mskangg** [comment]
Hi,
It still doesn't work. TT

**Comment by bokub** [comment]
You have to use a `if` condition.

The guard [will just transpile](https://www.typescriptlang.org/play?#code/FAYw9gdgzgLgBAWwIYAc4F44G8C+clT4QCeA3KJLHADYCWEAphnAOQvnjTwpIBOU9AOYAZJBEHMWAKyQA3AiF60UMFsGQoA2j35DR4gLoB+AHQ8YACyhmArlAsAKOowCUpIA) this

```ts
map[parsingLang]?.paths.push(line);
```

into this: 

```js
(_a = map[parsingLang]) === null || _a === void 0 ? void 0 : _a.paths.push(line);
```

which doesn't handle the case of `map[parsingLang]` being undefined...

**Comment by bokub** [comment]
@mskangg You have to re-generate your repo from the template or make the same edit in `src/linguist.js` !

**Comment by mskangg** [comment]
@bokub Oh my mistake.. 😂 Thanks for catching my mistake.
My gist works well with your help. Thx bro!
