### ISSUE TITLE
err : name of language and amount of code

### ISSUE THREAD

**Issue by Winning-Bean** [inokawa/lang-box#8]
My lang-box repository was created using this template.
Recently, I found this error.

<img width="453" alt="스크린샷 2021-08-02 오후 9 26 12" src="https://user-images.githubusercontent.com/53260922/127861636-e87db6c1-2981-4e37-97ee-cc6664e64852.png">

Percentages are fine, but language name and amount of code are not printed properly.
I would like to continue using this project.
Give me ideas please.

Thanks!!

**Comment by inokawa** [comment]
@Winning-Bean 
This gist updater broke by change of dependent library several days ago, but fixed now by #7.
Could you regenarate your repository please?

**Comment by Winning-Bean** [comment]
@inokawa
I tried your idea and I solved this issue.
Thank you! 👍
